# Generated by Django 4.0.4 on 2022-04-27 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='main',
            old_name='numbers',
            new_name='number',
        ),
        migrations.RenameField(
            model_name='main',
            old_name='users',
            new_name='user',
        ),
    ]
