name: action

on:
  push:
    branches: 
      - main
      - devops
      
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2
      - name: Restart gunicorn
        run: |
          sudo systemctl restart gunicorn


      - name: Restart nginx
        run: |
          sudo systemctl restart nginx

